// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4YJ8n_NDqX4Rl6ErIQer7MEHL90hjFKE',
    appId: '1:417912655444:web:75551e302c7a308420a7c1',
    messagingSenderId: '417912655444',
    projectId: 'fir-flatter',
    authDomain: 'fir-flatter.firebaseapp.com',
    storageBucket: 'fir-flatter.appspot.com',
    measurementId: 'G-34X30ZWX1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCn80ApUQ-fK-o8B8HCjlqpJMYrk4YO2E',
    appId: '1:417912655444:android:645152497fe2252020a7c1',
    messagingSenderId: '417912655444',
    projectId: 'fir-flatter',
    storageBucket: 'fir-flatter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhJqR8pM4p2TMsLgL6M0N3G5SyOmsGJj4',
    appId: '1:417912655444:ios:ecd2fc654bc6f72f20a7c1',
    messagingSenderId: '417912655444',
    projectId: 'fir-flatter',
    storageBucket: 'fir-flatter.appspot.com',
    iosClientId: '417912655444-9007p52ft29pdm7aeh2l4iup9agg74kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhJqR8pM4p2TMsLgL6M0N3G5SyOmsGJj4',
    appId: '1:417912655444:ios:ecd2fc654bc6f72f20a7c1',
    messagingSenderId: '417912655444',
    projectId: 'fir-flatter',
    storageBucket: 'fir-flatter.appspot.com',
    iosClientId: '417912655444-9007p52ft29pdm7aeh2l4iup9agg74kf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFirebase',
  );
}
